
CREATE TABLE EMPRESA(
	EMP_ID INTEGER NOT NULL,
	EMP_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
	EMP_NOME_FANTASIA VARCHAR(200),
	EMP_CNPJ VARCHAR(14) NOT NULL,
    EMP_ENDERECO VARCHAR(150),
    EMP_NUMERO INTEGER,
    EMP_CIDADE VARCHAR(100),
    EMP_BAIRRO VARCHAR(150),
    EMP_UF VARCHAR(2),
	CONSTRAINT PK_EMPRESA PRIMARY KEY (EMP_ID)
);
CREATE SEQUENCE GEN_EMPRESA;

CREATE TABLE PESSOA(
	PES_ID INTEGER NOT NULL,
	PES_NOME VARCHAR(200) NOT NULL,
	PES_DATA_NASC DATE,
	PES_CPF VARCHAR(11),
    PES_ENDERECO VARCHAR(150),
    PES_NUMERO INTEGER,
    PES_CIDADE VARCHAR(100),
    PES_BAIRRO VARCHAR(150),
    PES_UF VARCHAR(2),
	CONSTRAINT PK_PESSOA PRIMARY KEY (PES_ID)
);
CREATE SEQUENCE GEN_PESSOA;

CREATE TABLE FUNCIONARIO(
	FUN_ID INTEGER NOT NULL,
	FUN_COD_EMP INTEGER NOT NULL,
	FUN_COD_PESSOA INTEGER NOT NULL,
	FUN_PIS VARCHAR(11),
	FUN_DATA_ADM DATE,
	FUN_DATA_DEMI DATE,
	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (FUN_ID),
	CONSTRAINT FK_FUNC_PESSOA FOREIGN KEY (FUN_COD_PESSOA) REFERENCES PESSOA(PES_ID),
	CONSTRAINT FK_FUNC_EMPRESA FOREIGN KEY (FUN_COD_EMP) REFERENCES EMPRESA(EMP_ID)
);
CREATE SEQUENCE GEN_FUNCIONARIO;

CREATE TABLE FUNCAO(
	FNC_ID INTEGER NOT NULL,
	FNC_DESC VARCHAR(200) NOT NULL,
	FNC_SITUACAO CHAR(1) NOT NULL,
	CONSTRAINT PK_FUNCAO PRIMARY KEY (FNC_ID)
);
CREATE SEQUENCE GEN_FUNCAO;

CREATE TABLE FUNCIONARIOXFUNCAO(
	FXF_ID INTEGER NOT NULL,
	FXF_COD_FUNC INTEGER NOT NULL,
	FXF_COD_FUNCAO INTEGER NOT NULL,
	FXF_DATA_INI DATE NOT NULL,
	FXF_DATA_FIM DATE,
	CONSTRAINT PK_FUNCIONARIOXFUNCAO PRIMARY KEY (FXF_ID),
	CONSTRAINT FK_FUNCXFNC_FUNCIONARIO FOREIGN KEY (FXF_COD_FUNC) REFERENCES FUNCIONARIO(FUN_ID),
	CONSTRAINT FK_FUNCXFNC_FUNCAO FOREIGN KEY (FXF_COD_FUNCAO) REFERENCES FUNCAO(FNC_ID)
);
CREATE SEQUENCE GEN_FUNCIONARIOXFUNCAO;

CREATE TABLE ATIVIDADE(
	ATV_ID INTEGER NOT NULL,
	ATV_DESC VARCHAR(200) NOT NULL,
	ATV_SITU CHAR(1) NOT NULL,
	CONSTRAINT PK_ATIVIDADE PRIMARY KEY (ATV_ID)
);
CREATE SEQUENCE GEN_ATIVIDADE;


CREATE TABLE ATIVXFUNCAO(
	AXF_ID INTEGER NOT NULL,
	AXF_COD_ATIVIDADE INTEGER NOT NULL,
	AXF_COD_FUNCAO INTEGER NOT NULL,
	CONSTRAINT PK_ATIVXFUNCAO PRIMARY KEY (AXF_ID),
	CONSTRAINT FK_AXF_ATIVIDADE FOREIGN KEY (AXF_COD_ATIVIDADE) REFERENCES ATIVIDADE(ATV_ID),
	CONSTRAINT FK_AXF_FUNCAO FOREIGN KEY (AXF_COD_FUNCAO) REFERENCES FUNCAO(FNC_ID)
);
CREATE SEQUENCE GEN_ATIVXFUNCAO;

CREATE TABLE TAREFA(
	TAR_ID INTEGER NOT NULL,
	TAR_DESC VARCHAR(200) NOT NULL,
	TAR_GRAU_PERIGO INTEGER NOT NULL,
	CONSTRAINT PK_TAREFA PRIMARY KEY (TAR_ID)
);
CREATE SEQUENCE GEN_TAREFA;

CREATE TABLE TAREFAXATIVIDADE(
	TXA_ID INTEGER NOT NULL,
	TXA_COD_TAREFA INTEGER NOT NULL,
	TXA_COD_ATIIDADE INTEGER NOT NULL,
	TXA_SITU CHAR(1) NOT NULL,
	CONSTRAINT PK_TAREFAXATIVIDADE PRIMARY KEY (TXA_ID),
	CONSTRAINT FK_TXA_ATIVIDADE FOREIGN KEY (TXA_COD_ATIIDADE) REFERENCES ATIVIDADE(ATV_ID),
	CONSTRAINT FK_TXA_TAREFA FOREIGN KEY (TXA_COD_TAREFA) REFERENCES TAREFA(TAR_ID)
);
CREATE SEQUENCE GEN_TAREFAXATIVIDADE;

CREATE TABLE AVALIACAO(
	AVL_ID INTEGER NOT NULL,
	AVL_COD_FUNC INTEGER,
	AVL_COD_ATIVIDADE INTEGER NOT NULL,
	AVL_DESC VARCHAR(200) NOT NULL,
	AVL_DATA TIMESTAMP NOT NULL,
	CONSTRAINT PK_AVALIACAO PRIMARY KEY (AVL_ID),
	CONSTRAINT FK_AVL_FUNCIONARIO FOREIGN KEY (AVL_COD_FUNC) REFERENCES FUNCIONARIO(FUN_ID),
	CONSTRAINT FK_AVL_ATIVIDADE FOREIGN KEY (AVL_COD_ATIVIDADE) REFERENCES ATIVIDADE(ATV_ID)
);
CREATE SEQUENCE GEN_AVALIACAO;

CREATE TABLE CICLO(
	CCL_ID INTEGER NOT NULL,
	CCL_COD_AVAL INTEGER NOT NULL,
	CCL_SEQ INTEGER NOT NULL,
	CONSTRAINT PK_CICLO PRIMARY KEY (CCL_ID)
);
CREATE SEQUENCE GEN_CICLO;

CREATE TABLE CICLO_DETALHE(
	CD_ID INTEGER NOT NULL,
	CD_COD_TAREFA INTEGER NOT NULL,
	CD_COD_CICLO INTEGER NOT NULL,
	CD_SEGUNDOS INTEGER,
	CONSTRAINT PK_CICLO_DETALHE PRIMARY KEY (CD_ID),
	CONSTRAINT FK_CD_TAREFA FOREIGN KEY (CD_COD_TAREFA) REFERENCES TAREFA(TAR_ID),
	CONSTRAINT FK_CD_CICLO FOREIGN KEY (CD_COD_CICLO) REFERENCES CICLO(CCL_ID)
);
CREATE SEQUENCE GEN_CICLO_DETALHE;

	CREATE TABLE USUARIO(
		USU_ID INTEGER NOT NULL,
		USU_COD_PESSOA INTEGER NOT NULL,
		USU_USUARIO VARCHAR(30) NOT NULL,
		USU_SENHA VARCHAR(32) NOT NULL,
		USU_EMAIL VARCHAR(100),
		USU_ADM BOOLEAN DEFAULT FALSE NOT NULL,
		CONSTRAINT PK_USUARIO PRIMARY KEY (USU_ID),
		CONSTRAINT FK_USU_PESSOA FOREIGN KEY (USU_COD_PESSOA) REFERENCES PESSOA(PES_ID)
	);
CREATE SEQUENCE GEN_USUARIO;








